version: '3'
services:
  go-backend:
    build:
      context: .  # The root level for the Go backend
      dockerfile: Dockerfile  # Go Dockerfile at root level
    ports:
      - "8000:8000"  # Expose port 8000 for the Go backend
    networks:
      - my-network

  react-frontend:
    build:
      context: ./image-primitive  # React app is in the 'image-primitive' directory
      dockerfile: Dockerfile  # React Dockerfile inside the 'image-primitive' directory
    ports:
      - "8000:8000"  # Expose port 80 for React frontend
    depends_on:
      - go-backend  # Ensure the Go backend starts before the React frontend
    networks:
      - my-network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount your Nginx config file
    ports:
      - "80:80"  # Expose port 80 for Nginx to forward traffic
    depends_on:
      - react-frontend
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
