version: '3.8'
services:
  go-backend:
    build:
      context: .  # The root level for the Go backend
      dockerfile: Dockerfile  # Go Dockerfile at root level
    ports:
      - "8080:8080"  # Expose port 8000 for the Go backend
    networks:
      - my-network

  react-frontend:
    build:
      context: ./image-primitive  # React app is in the 'image-primitive' directory
      dockerfile: Dockerfile  # React Dockerfile inside the 'image-primitive' directory
    depends_on:
      - go-backend  # Ensure the Go backend starts before the React frontend
    networks:
      - my-network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount your Nginx config file
      - ./image-primitive/dist:/usr/share/nginx/html:ro  # Mount the React build output
    ports:
      - "80:80"  # Expose port 80 for Nginx to forward traffic
    depends_on:
      - react-frontend
      - go-backend
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
